disk_types:
- name: 5GB
  cloud_properties:
    encrypted: true
    type: gp2
  disk_size: 5120
- name: 10GB
  cloud_properties:
    encrypted: true
    type: gp2
  disk_size: 10240
- name: 100GB
  cloud_properties:
    encrypted: true
    type: gp2
  disk_size: 102400

vm_types:
- name: minimal
  cloud_properties:
    ephemeral_disk:
      size: 10240
      type: gp2
    instance_type: t2.small
- name: small
  cloud_properties:
    ephemeral_disk:
      size: 10240
      type: gp2
    instance_type: t2.small
- name: small-highmem
  cloud_properties:
    instance_type: t2.medium
- name: compilation
  cloud_properties:
    ephemeral_disk:
      size: 10240
      type: gp2
    instance_type: c4.large

vm_extensions:
- name: api_ephemeral_disk
  cloud_properties:
    ephemeral_disk:
      size: 8000
      type: gp2
- name: cell_ephemeral_disk
  cloud_properties:
    ephemeral_disk:
      size: 15000
      type: gp2
- name: cf-router-network-properties
  cloud_properties:
    elbs: [((system_lb))]
- name: cf-tcp-router-network-properties
  cloud_properties:
    elbs: []
- name: diego-ssh-proxy-network-properties
  cloud_properties:
    elbs: []

azs:
- name: z1
  cloud_properties:
    availability_zone: ((availability_zone))

networks:
- name: default
  type: manual
  subnets:
  - range: ((private_subnet_range))
    az: z1
    cloud_properties:
      security_groups: [((security_group))]
      subnet: ((subnet_id))
    gateway: ((gateway_ip))
    reserved: [((gateway_ip))/30]

compilation:
  az: z1
  network: default
  reuse_compilation_vms: true
  vm_extensions: [cell_ephemeral_disk]
  vm_type: compilation
  workers: 3
